### ISSUE TITLE
Dokumentacja

### ISSUE THREAD

**Issue by PogromcaPapai** [PogromcaPapai/Larch#22]
- readme
- trzeba wybrać licencję xdd
- wiki
- tłumaczenie readme na angielski (z radością przyjmę pomoc @barburaadamska)

**Comment by PogromcaPapai** [comment]
https://www.makeareadme.com

**Comment by barburaadamska** [comment]
lekko

**Comment by PogromcaPapai** [comment]
Czy warto przepisać dokumentację na polski?

**Comment by PogromcaPapai** [comment]
Czekamy na plany Roberta, może jakaś integracja

**Comment by PogromcaPapai** [comment]
Imo warto utworzyć też możliwość tworzenia readme dla pluginów, gdzie autor może dopisać co chce
